### ISSUE TITLE
Multiple packages

### ISSUE THREAD

**Issue by frmdstryr** [Akrog/pinliner#1]
Can this inline multiple packages? Say for instance, a folder of a few different packages.

**Comment by Akrog** [comment]
It is not currently supported, but in some places [in the code](https://github.com/Akrog/pinliner/blob/c1f4e60e484d52c5fddbbcad1cf668b4f401aabf/pinliner/pinliner.py#L175-L176) it has been considered as a future feature.

If this is something that would be useful to you I'll add it.

**Comment by frmdstryr** [comment]
Yes, I did see that . I made a few tests to try it out (multiple modules didn't work) but it was able to inline the entire tornado library :+1: .  

Also, maybe should be in separate issues, but I have two other "wishlist" items. 
1. Include modules (root level)
2. Inline and load precompiled pyc/pyo files instead of pure py files. 

My "end goal" would be to inline the whole python standard library (excluding any shared libraries) and site-packages into one module. I think it could potentially be very useful for the https://github.com/kivy/python-for-android/ project. I'm envisioning something like a [webpack](https://github.com/webpack/webpack) for python.

It would be interesting to benchmark if it's faster to load from one file vs multiple. Any thoughts?

Thanks!

**Comment by Akrog** [comment]
Including modules would be tricky, because we would have to ensure entry points are available for the loaded libraries only at runtime, we would also have to take care of scripts and they should be available if we execute them inside our application, take care of the additional files section, and we would probably have to figure out what to do with extension modules...  Although partial support could be possible.

Initially I considered including precompiled files but doing so would remove of of the great benefits of Python: being able to run anywhere.  Since Python bytecode changes from Python version to version you would break an application if you just upgraded your system from Python 2.7.12 to 2.7.13.  You would also lose the possibility of having meaningful stack traces since they require the source code.

I haven't really evaluated what it would take to inline the whole standard library, but it's very likely to turn into a nightmare...

I don't anticipate any significant speed improvement from loading everything from a single file.

**Comment by Akrog** [comment]
I have implemented the multi package import, it will be included in the next release, until then you can try it installing directly from master: `pip install git+https://https://github.com/Akrog/pinliner.git`

**Comment by frmdstryr** [comment]
Great work!

I think partial support for modules would be sufficient. Currently all compiled extensions (.so/.dylib files) work using a custom loader anyways (similar to how CX_Freeze does it).

I know the stack traces work fine when using only compiled files as p4a has been using only .pyo files for almost a year now (even if source py files aren't there).  Still, It would be nice to at least have the option to do this.

Thank you! Will try as soon as I get some free time.
